url: "gbkey.club"
baseurl: ""

# Site settings
title: Granite Bay Key Club
email: gbhskeyclub@gmail.com
description: Granite Bay High School Key Club's official website has all the information you'll need about our fun events and amazing club!


# Team names, titles and social links
people:
- name: Noelle Prange
  pic: 1
  position: President
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Lucas Souza
  pic: 2
  position: Vice President
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Abigail Young
  pic: 3
  position: Vice President
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Nithila Shanmugam
  pic: 4
  position: Secretary
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Noah Fang
  pic: 5
  position: Treasurer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Pavan Kumar
  pic: 6
  position: Spirit Coordinator
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #


- name: Aveed Gorji
  pic: 7
  position: Editor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: fa-solid fa-r # Remind
    url: http://www.remind.com/join/gbkey2223
  - title: fab fa-instagram # Instagram
    url: http://instagram.com/gbhskeyclub
  - title: fab fa-twitter # Twitter
    url: http://twitter.com/gbkeyclub

# Postal address (add as many lines as necessary)
address:
  - line: 1 Grizzly Way
  - line: Granite Bay, CA 95746

# Build settings
markdown: kramdown
permalink: pretty