url: "gbkey.club"
baseurl: ""

# Site settings
title: Granite Bay Key Club
email: gbhskeyclub@gmail.com
description: Granite Bay High School Key Club's official website has all the information you'll need about our fun events and amazing club!

# Build settings
markdown: kramdown
permalink: pretty